Feature: every time start api-server ,create a new grafana key
tricorder-observability/Starship pull request #121
Opened 2023-02-26 14:08 UTC by zh9310

every time start api-server ,create a new grafana key. https://github.com/tricorder-observability/starship/issues/81

2023-02-26 15:24 UTC, nascentcore-eng requested changes
You need to add a test over this feature.
I.e., test that each getting grafana API key twitch will result into 2 API keys created on Grafana server

2023-02-26 15:24 UTC, nascentcore-eng commented on src/api-server/http/grafana/auth_token.go
> +	"log"
Use src/utils/log

2023-02-26 15:24 UTC, nascentcore-eng commented on src/api-server/http/grafana/auth_token.go
> +		return err
Use src/utils/errors.Wrap() to wrap this error with context
See src/utils/errors_test.go for how to use the function

2023-02-26 15:24 UTC, nascentcore-eng commented on src/api-server/http/grafana/auth_token.go
> +		// }
Remove

2023-02-26 15:24 UTC, nascentcore-eng commented on src/api-server/http/grafana/auth_token.go
> +	return err
```
if err != nil {
  return errors.Wrap("...", "...", err)
}
return nil
```
Do not change typical pattern, instead, always stick with the established pattern

2023-02-27 04:40 UTC, nascentcore-eng requested changes

2023-02-27 04:40 UTC, nascentcore-eng commented on src/api-server/http/grafana.go
> +	GrafanaAPIKeyMap map[string]string
change to private members

2023-02-27 04:40 UTC, nascentcore-eng commented on src/api-server/http/grafana.go
> +func (g *GrafanaManagement) getGrafanaKey(apiPath, apiName string) (string, error) {
apiName not used? If so, apiName should be removed.

2023-02-27 04:40 UTC, nascentcore-eng commented on src/api-server/http/grafana.go
> +		return "", fmt.Errorf("get grafana api token error %v", err)
Use `src/utils/errors.Wrap()` to wrap error

2023-02-27 04:40 UTC, nascentcore-eng commented on src/api-server/http/grafana.go
> +	GrafanaAPIKeyMap map[string]string
Comment on the purpose of this map

2023-02-27 04:40 UTC, nascentcore-eng commented on src/api-server/http/grafana.go
>  	}
Do you need this? I though you can just call `g.GrafanaAPIKeyMap = make(map[string]string)` in the NewGrafanaManagement() function.

And you should always prefer to have a New() function to build the data structure, instead of having all members public

2023-02-27 04:40 UTC, nascentcore-eng commented on src/api-server/http/grafana.go
>  }
Return the actual key, not just error

This way you can rename this to GetGrafanaAPIToken()
And rename getGrafanaKey() to createGrafanaAPIToken()

2023-02-27 14:00 UTC, zh9310 commented on src/api-server/http/grafana.go
>  }
This method is only initialized once at startup, and no return value is required

2023-02-27 15:29 UTC, nascentcore-eng approved these changes

2023-02-27 15:29 UTC, merged