feat(api-server): add list agent api
tricorder-observability/Starship pull request #190
Opened 2023-03-11 18:29 UTC by owl-ltt

# Describe your changes

1.  add list agent API expose to `/api/listAgent`

## Issue
- [ ] If this PR fixes an issue, paste the link below

## Test:
- [ ] What tests are done for this PR

2023-03-12 04:00 UTC, nascentcore-eng requested changes
There needs to be tests for ListAgent API

2023-03-12 04:00 UTC, nascentcore-eng commented on src/api-server/http/api/api.go
> +	LIST_AGENT      = "/listAgent"
Should we use /api/agents path, and 'GET' method, which is more aligned with RESTFul convention?

2023-03-12 04:00 UTC, nascentcore-eng commented on src/api-server/http/module_manager.go
> +// @Param			   fields	 query	string	false  "query field search like 'id,name,createTime'"
What's the meaning of each field here?

2023-03-12 04:00 UTC, nascentcore-eng commented on src/api-server/http/module_manager.go
> +func (mgr *ModuleManager) listAgent(req ListModuleReq) ListAgentResp {
Why use ListModuleReq as argument for listAgent?
You can use type alias to define a ListAgentReq instead.

2023-03-12 04:00 UTC, nascentcore-eng commented on src/api-server/http/module_manager_test.go
> +}
Stop using t *testing.T in test helper, let this return error

2023-03-12 05:29 UTC, owl-ltt commented on src/api-server/http/module_manager.go
> +// @Param			   fields	 query	string	false  "query field search like 'id,name,createTime'"
this field contained database table column names, we can set these fields to determine which column will be selected and returned.

2023-03-12 08:29 UTC, owl-ltt commented on src/api-server/http/api/api.go
> +	LIST_AGENT      = "/listAgent"
add this todo comment

2023-03-13 13:59 UTC, nascentcore-eng approved these changes

2023-03-13 13:59 UTC, nascentcore-eng commented on src/api-server/http/api/api.go
> +	// todo: change to resful style
TODO should have assignee:
And 
TODO(...):

2023-03-13 13:59 UTC, merged