Feature: add load module cli
tricorder-observability/Starship pull request #54
Opened 2023-02-19 10:05 UTC by zh9310

Load local module to sqlite db file

2023-02-19 14:13 UTC, nascentcore-eng commented on src/load/README.md
> +load local module to sqlit db file
sqlit -》SQLite

2023-02-19 14:13 UTC, nascentcore-eng commented on src/load/load/load.go
> +	loadCmd.Flags().StringVarP(&dbFilePath, "db-file-path", "d", dbFilePath, "The file path of sqlit db.")
Change this flag to actually point to the path of the db file, not just the parent directory.

2023-02-19 14:13 UTC, nascentcore-eng commented on src/load/load/load.go
> +	loadCmd.Flags().StringVarP(&dbFilePath, "db-file-path", "d", dbFilePath, "The file path of sqlit db.")
This flag should be called --output (short name -o)

2023-02-19 14:13 UTC, nascentcore-eng commented on src/load/load/load.go
> +	loadCmd.Flags().StringVarP(&moduleFilePath, "module-file-path", "m",
Is this the same name as the other cli? If not, should make sure they are the same.

2023-02-19 14:13 UTC, nascentcore-eng commented on src/load/load/load.go
> +	loadCmd.Flags().StringVarP(&moduleFilePath, "module-file-path", "m",
Also mark flag as required if necessary

I.e. if missing a flag would cause command to fail, mark this flag as required

Take a look at the other cli for example

2023-02-19 14:13 UTC, nascentcore-eng commented on src/load/load/load.go
> +	loadCmd.Flags().StringVarP(&moduleFilePath, "module-file-path", "m",
Remember to consider mark the other flags as required as well

2023-02-19 14:13 UTC, nascentcore-eng commented on src/load/load/root.go
> +	Short: "The CLI (Command Line Interface) for starship",
This is wrong
Should be
"""
CLI tool to load pre-built eBPF+WASM modules into SQLite DB file
"""

2023-02-19 14:13 UTC, nascentcore-eng commented on src/load/load/root.go
> +	Long:  `CLI to manage starship observe modules.`,
CLI tool to load pre-built eBPF+WASM modules into SQLite DB file. Requires to specify the paths to BCC source file, WASM compiled binary object file, and module description in JSON format. The content of these files are written to the specified SQLite db file. We use this tool to load pre-built eBPF+WASM modules into Starship's official release.

2023-02-19 14:13 UTC, nascentcore-eng commented on src/load/load/root.go
> +// Execute adds all child commands to the root command and sets flags appropriately.
This comment is completely wrong

2023-02-19 14:13 UTC, nascentcore-eng commented on src/load/load/root.go
> +	rootCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")
Do you need this?

Seems not needed at all.

2023-02-20 12:28 UTC, zh9310 commented on src/load/load/load.go
> +	loadCmd.Flags().StringVarP(&dbFilePath, "db-file-path", "d", dbFilePath, "The file path of sqlit db.")
The db file address is fixed in the sqlite util. https://github.com/tricorder-observability/starship/blob/fd419481e40fb5442864019c37bd225bdc14b334/src/utils/sqlite/sqlite.go#L16

2023-02-20 12:30 UTC, zh9310 commented on src/load/load/load.go
> +	loadCmd.Flags().StringVarP(&moduleFilePath, "module-file-path", "m",
Same with the cli definition of module. https://github.com/tricorder-observability/starship/blob/fd419481e40fb5442864019c37bd225bdc14b334/src/cli/cmd/module/create.go#L63

2023-02-20 16:19 UTC, nascentcore-eng requested changes

2023-02-20 16:19 UTC, nascentcore-eng commented on src/load/README.md
> +chmod +x /usr/local/bin/starship-load
You don't need this, the file should already have executable permission

2023-02-20 16:19 UTC, nascentcore-eng commented on src/load/load/load.go
> +)
Please stop using package global variable...

2023-02-20 16:19 UTC, nascentcore-eng commented on src/load/load/root.go
> +// Execute load command.
Remove

Do not repeat what the code shows, that's just wasting reader's time.

2023-03-01 12:49 UTC, nascentcore-eng approved these changes

2023-03-01 12:49 UTC, merged