Feature: add swagger document
tricorder-observability/Starship pull request #55
Opened 2023-02-19 14:11 UTC by zh9310

add swagger document

2023-02-20 10:00 UTC, nascentcore-eng requested changes

2023-02-20 10:00 UTC, nascentcore-eng commented on src/api-server/cmd/docs/swagger.json
> +{
Is this file automatically generated?

2023-02-20 10:00 UTC, nascentcore-eng commented on src/api-server/cmd/main.go
> +// @license.name  Apache 2.0
We use AGPL, not Apache, please check the repo root for the actual license version

2023-02-20 10:00 UTC, nascentcore-eng commented on src/api-server/cmd/main.go
> +	docs.SwaggerInfo.Schemes = []string{"http", "https"}
These are completely wrong...

2023-02-20 10:00 UTC, nascentcore-eng commented on src/api-server/http/http.go
> +	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
Document in the comment about the purpose of this

2023-02-20 10:00 UTC, nascentcore-eng commented on src/api-server/http/module_manager.go
> +// @Param			   account	body		module.Module	true	"Add module"
Why there is long spaces separating `@param` & `account`

2023-02-20 10:00 UTC, nascentcore-eng commented on src/api-server/http/module_manager.go
> +// @Param			fields	query		string	false	"query field search like 'id,name,createTime'"
Same here

2023-02-20 10:00 UTC, nascentcore-eng commented on src/api-server/cmd/docs/README.md
> +http://host:port/swagger/index.html
Describe how this module works, i.e., the mechanism of swagger generating docs.

2023-02-20 10:00 UTC, nascentcore-eng commented on src/api-server/cmd/docs/docs.go
> +// Code generated by swaggo/swag. DO NOT EDIT
Why place docs under src/api-server/cmd?

src/api-server/cmd is for storing executables, docs are not exectuable, right?

2023-02-20 10:00 UTC, nascentcore-eng commented on src/api-server/cmd/docs/swagger.yaml
> +definitions:
Is this automatically generated?

2023-02-20 10:00 UTC, nascentcore-eng commented on src/api-server/cmd/docs/README.md
> +
Also need to explain the purpose of .json and .yaml files under this directory.

2023-02-20 15:05 UTC, zh9310 commented
Too many backward main branches

2023-02-21 12:16 UTC, zh9310 commented on src/api-server/cmd/docs/swagger.json
> +{
This file is not required.
https://github.com/tricorder-observability/starship/pull/65

2023-02-21 12:58 UTC, closed without merging