Feature: get apiaddress for kubernetes cluster.
tricorder-observability/Starship pull request #74
Opened 2023-02-21 11:00 UTC by yaoyaoio

add: get apiaddress for kubernetes cluster.

I tested it on aliyun ack cluster.

<img width="781" alt="CleanShot 2023-02-21 at 18 59 46@2x" src="https://user-images.githubusercontent.com/14813534/220326943-b2257f25-c42d-4439-8185-0fe46c25fcaf.png">

2023-02-21 11:41 UTC, nascentcore-eng reviewed
You might need to run `tools/cleanup.sh` on your local repo to fix the build issue

https://github.com/tricorder-observability/starship/blob/main/README.md#contributing
(I just added after seeing the CI test failures, sorry for the negligence)

2023-02-21 11:41 UTC, nascentcore-eng commented on src/cli/pkg/kubernetes/common.go
> +	return service.Spec.ClusterIP, nil
Need comments for all these functions

2023-02-21 13:41 UTC, nascentcore-eng commented
Take a look at the CI test failures, and see if you could fix them.

2023-02-21 13:41 UTC, nascentcore-eng commented
Run tools/cleanup.sh to fix some of the style issues and bazel build files issue.

The below are the failures in the CI pipeline.
![image](https://user-images.githubusercontent.com/112656580/220361525-c60c8fe3-eb32-4f00-acae-0391e495de11.png)

2023-02-21 13:43 UTC, yaoyaoio commented
ok. I fix these issues.

2023-02-23 08:21 UTC, yaoyaoio commented
I have made changes according suggestions Please review and CI test.

2023-02-23 12:24 UTC, nascentcore-eng requested changes

2023-02-23 12:24 UTC, nascentcore-eng commented on src/cli/cmd/module/module.go
> +				fmt.Println("connect to kubernetes failed, please use --api-address to set api address manually.")
If this happens, what's the exit code of the command?
I am not familiar with cobra @JaredTan95

2023-02-23 12:24 UTC, nascentcore-eng commented on src/cli/pkg/kubernetes/client.go
> +func GetClientForConfig(config *rest.Config) (*k8s.Clientset, error) {
This does not seem useful to be a independent helper function.
You can just directly call k8s.NewForConfig(config) in the caller of GetClientForConfig inside NewClient().

2023-02-23 12:24 UTC, nascentcore-eng commented on src/cli/pkg/kubernetes/client.go
> +func GetConfig() (*rest.Config, error) {
This should be private function

2023-02-23 12:24 UTC, nascentcore-eng commented on src/cli/pkg/kubernetes/common.go
> +var (
nit: const

2023-02-23 12:24 UTC, nascentcore-eng commented on src/cli/pkg/kubernetes/common.go
> +		return "", err
Use src/utils/errors.Wrap() to return contextual error message, see
https://github.com/tricorder-observability/starship/blob/05ed0bace56f58a49c7897e5ccf31acc76793d45/src/utils/errors/wrap_test.go#L30
for example,

2023-02-23 12:24 UTC, nascentcore-eng commented on src/cli/pkg/kubernetes/common.go
> +func GetService(client *k8s.Clientset, namespace, serviceName string) (*v1.Service, error) {
most of these function should be private, adjust them to private if not used outside of this package.

2023-02-23 12:47 UTC, oojimmy commented on src/cli/cmd/module/module.go
> +	//_ = ModuleCmd.MarkPersistentFlagRequired("api-address")
need to delete this,  not just annotation it.

2023-02-23 12:47 UTC, oojimmy commented on src/cli/pkg/kubernetes/common.go
> +		if port.Name == "serverhttp" {
"serverhttp" can be set by `const var` in the module, like `	DefaultNamespace   = "tricorder"`

2023-02-23 12:56 UTC, nascentcore-eng commented
The go file lacks license header.
You'll need to run tools/cleanup.sh to add the license header

2023-02-24 04:25 UTC, nascentcore-eng commented
Starship's CI/CD setup on GitHub might prevent you from releasing a dev image, we'll fix them separately.

2023-02-24 04:28 UTC, nascentcore-eng commented
I think my last request is to think about adding an automated test.

I could not come up a plan to implement a simple automated test, because there is no readily available testing fixture (like a fake kubernetes and kubectl local environment).

But I think you can write a brief doc on how to verify the correctness of this feature.

2023-02-24 07:24 UTC, JaredTan95 commented
> Starship's CI/CD setup on GitHub might prevent you from releasing a dev image, we'll fix them separately.

https://github.com/tricorder-observability/starship/pull/99 fixed docker build and push issue, you can rebase `main` branch to fix CI. @yaoyaoio

2023-02-24 15:31 UTC, yaoyaoio commented
> implement

Do you want me to implement a simple automated test to verify getting starship apiserver from kubernetes?

2023-02-25 05:50 UTC, nascentcore-eng commented
> 

Yes, if it's possible to do that.

If it's very complicated to do, then don't bother, manual testing is fine.

2023-02-25 12:11 UTC, yaoyaoio commented
Sorry I should’t have used merge.

2023-02-26 03:16 UTC, nascentcore-eng commented
Need to rebase on the main branch.

2023-02-27 09:29 UTC, nascentcore-eng approved these changes
Some minor suggestions

2023-02-27 09:29 UTC, nascentcore-eng commented on src/cli/cmd/module/module.go
> +	"log"
Use `"github.com/tricorder/src/utils/log"`
It's a drop-in replacement of "log"

2023-02-27 09:29 UTC, nascentcore-eng commented on src/cli/cmd/module/module.go
> +				log.Fatal("connect to kubernetes failed, please use --api-address to set api address manually.")
`connect to kubernetes failed`
change to
`Failed to connect to Kubernetes API Server`

2023-02-27 15:30 UTC, merged